bookstore1/urls.py
from django.urls import path

from .views import create_reminder, quote_list
from . import views

app_name = 'catalog'
urlpatterns = [
    path('reminder/', create_reminder, name="create_reminder"),
    path('quotes/', quote_list, name='pagination_quotes'),
    path('authors/', views.AuthorListView.as_view(), name='pagination_authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='detail_author')
    ]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookstore1.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

bookstore1/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000000)

    def __str__(self):
        return self.name


class Quote(models.Model):
    message = models.CharField(max_length=10000000)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f'Author: {self.author}'

bookstore1/forms.py
from django import forms
import datetime
from django.utils import timezone
from django.core.exceptions import ValidationError


class ReminderForm(forms.Form):
    email = forms.EmailField(max_length=100, required=True)
    text = forms.CharField(max_length=300, required=True)
    datetime = forms.DateTimeField(help_text="Example: YYYY-MM-DD hh:mm:ss")

    def clean_datetime(self):
        data = self.cleaned_data['datetime']
        today_now = timezone.now()
        if today_now < data < today_now + datetime.timedelta(days=2):
            raise ValidationError('Invalid date')
        return data

bookstore1/views.py
from django.http import Http404
from django.shortcuts import render
from django.views import generic

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .forms import ReminderForm
from .models import Author, Quote
from .tasks import send_mail
from django.views.decorators.cache import cache_page


def create_reminder(request):
    if request.method == 'POST':
        reminder_form = ReminderForm(request.POST)
        if reminder_form.is_valid():
            email = reminder_form.cleaned_data['email']
            text = reminder_form.cleaned_data['text']
            data = reminder_form.cleaned_data['datetime']
            message = "Message has sent successfully!"
            send_mail.apply_async((text, email), eta=data)
            return render(
                request,
                'bookstore1/create_reminder.html',
                {
                    'reminder_form': reminder_form,
                    'message': message,

                }
            )
    else:
        reminder_form = ReminderForm()
    return render(
        request,
        'bookstore1/create_reminder.html',
        {
            'reminder_form': reminder_form,
        }
    )


@cache_page(1)
def quote_list(request):
    quotes_list = Quote.objects.select_related('author').all()
    page = request.GET.get('page', 1)
    paginator = Paginator(quotes_list, 150)
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        raise Http404
    context = {'page_obj': page_obj}
    return render(request, 'bookstore1/pagination_quotes.html', context)


class AuthorListView(generic.ListView):
    model = Author
    queryset = Author.objects.all()
    paginate_by = 200
    template_name = 'bookstore1/pagination_authors.html'


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'bookstore1/detail_author.html'

bookstore1/templates/bookstore1/create_reminder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create reminder</title>
</head>
<body>
<h1>Create text message and send it to your email!</h1>

<form action= "{% url 'reminder:create_reminder' %}" method = "post">
    {% csrf_token %}
    {{ reminder_form.as_p }}
    <input type="submit" name="submit" value="Send email">
</form>
{% if message %}
    <h3> {{ message }} </h3>
{% endif %}

</body>
</html>

bookstore1/templates/bookstore1/detail_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail author</title>
</head>
<body>
<h1>Detail about {{ object }}</h1>
    <ul>ID: {{ object.id }}</ul>
    <ul>Name: {{ object.name }}</ul>
    <ul>Description: {{ object.description }}</ul>
<ul><a href="{% url 'booksre1:pagination_quotes' %}">Back to quotes list</a></ul>
<ul><a href="{% url 'booksre1:pagination_authors' %}">Look to authors list</a></ul>
</body>
</html>

bookstore1/templates/bookstore1/pagination_authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authors</title>
</head>
<body>
<ul><a href="{% url 'booksre1:pagination_quotes' %}">Back to quotes list</a></ul>
  <h1>List of authors</h1>

  {% if author_list %}
    <ul>
      Count of authors: {{ paginator.count }}

      {% for obj in author_list %}
          <li><a href="{% url 'booksre1:todetail_author' pk=obj.id %}"> {{ obj }}</a></li></li>
      {% endfor %}

    </ul>
  {% else %}
    <p>No more authors on this site</p>
  {% endif %}
<div>
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}">previous</a>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <a>{{ i }}</a>
            {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}">next</a>
        {% endif %}
    {% endif %}
    </div>
</body>
</html>

bookstore1/templates/bookstore1/pagination_quotes.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Quotes</title>
</head>
<body>
</div>
	<center>
		{%if page_obj.has_previous %}
			<a href="?page={{page_obj.previous_page_number}}">Previous</a>
		{% endif %}
		<span>
    {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <a>{{ i }}</a>
            {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
            {% endif %}
        {% endfor %}
        </span>
		{%if page_obj.has_next %}
			<a href="?page={{page_obj.next_page_number}}">Next</a>
		{% endif %}
	</center>
	<div class="container">
		{% for obj in page_obj.object_list %}
            <li>"{{obj.message}}" written by <a href="{% url 'booksre1:detail_author' pk=obj.author.id %}">{{obj.author.name}}</a></li>
        <p>{{obj.content}}</p>

			<hr/>
		{% endfor %}</div>
</body>
</html>